services:
  nginx:
    build:
      context: nginx
      dockerfile: ../_docker/Dockerfile.proxy
    ports:
      - "8080:80"
    volumes:
      - ./project:/var/www
    networks:
      - default
    depends_on:
      - app

  app:
    build:
      context: project
      dockerfile: ../_docker/Dockerfile.app
    ports:
      - 9000:80
    volumes:
      - ./project:/var/www
    networks:
      - default
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      - db

  nodejs:
    build:
      context: project
      dockerfile: ../_docker/Dockerfile.node
    ports:
      - "5173:5173"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./project:/var/www
      - /var/www/node_modules
    networks:
      - default

  db:
    image: mysql
    restart: always
    user: mysql
    secrets:
      - db-password
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=todo_app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123123
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - default
    expose:
      - 3306

volumes:
  node_modules:
secrets:
  db-password:
    file: secrets/db-password.txt

networks:
  default:
    driver: bridge
